import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E5E5E5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    forgotText: {
        fontSize: 15,
        color: '#2E3283',
        marginTop: 5,
        marginBottom: 10,
    },
    inputView: {
        width: '80%',
        backgroundColor: '#dedede',
        borderRadius: 5,
        height: 50,
        marginTop: 5,
        marginBottom: 5,
        justifyContent: 'center',
    },
    inputPass: {
        width: '80%',
        backgroundColor: '#dedede',
        borderRadius: 5,
        height: 50,
        marginTop: 5,
        marginBottom: 5,
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
    },
    icon: {
        width: 24,
        height: 14,
        marginRight: 15,
    },
    inputText: {
        marginLeft: 15,
        height: 50,
        color: '#000000',
        fontSize: 16,
    },
    passText: {
        width: '80%',
        marginLeft: 15,
        height: 50,
        color: '#000000',
        fontSize: 16,
    },
    pleaseText: {
        height: 50,
        color: '#5B5B5B',
        fontSize: 22,
    },
    image: {
        margin: 20,
        width: 247,
        height: 58.5,
    },
    loginBtn: {
        width: '80%',
        backgroundColor: '#2E3283',
        borderRadius: 5,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 5,
    },
    loginText: {
        fontSize: 16,
        color: 'white',
    },
    loginWith: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
    },
    lineView: {
        backgroundColor: '#959595',
        height: 2,
        width: 95,
        marginHorizontal: 10,
    },
    loginWithText: {
        color: '#2E3283',
        fontSize: 15,
        marginHorizontal: 10,
    },
    imageView: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
    },
    imageCon: {
        margin: 10,
        width: 46,
        height: 46,
        marginHorizontal: 20,
    },
    appVersion: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
    },
    appText: {
        fontSize: 16,
        color: '#828282',
        marginHorizontal: 10,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        height: 40,
        width: '100%',
        backgroundColor: '#DEDEDE',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },

    backLogo: {
        position: 'absolute',
        top: 10,
        left: 10,
        alignSelf: 'flex-start',
        width: '100%',
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
    },

    pleaseText: {
        height: 50,
        color: '#5B5B5B',
        fontSize: 22,
    },
    banner: {
        top: -140,
        width: '100%',
        height: '27%',
    },
    moreBtn: {
        bottom: -110,
        width: '35%',
        backgroundColor: '#2E3283',
        borderRadius: 10,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 5,
    },
    moreText: {
        fontSize: 21,
        color: 'white',
    },
    smallImages: {
        width: 80,
        height: 80,
    },
});
